version: "3"
services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    volumes:
      - base_volume:/project
    environment:
      JUPYTER_TOKEN: "secret_here"
volumes:
  base_volume:
    external: true
